version: '3.9'
services:
    nginx:
        image: fractalnetworks/gateway:latest
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        ports:
            - 80:80
            - 443:443
