  link:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: ${LINK_DOMAIN}
      EXPOSE: ${EXPOSE}
      GATEWAY_CLIENT_WG_PRIVKEY: ${WG_PRIVKEY}
      GATEWAY_LINK_WG_PUBKEY: ${GATEWAY_LINK_WG_PUBKEY}
      GATEWAY_ENDPOINT: ${GATEWAY_ENDPOINT}
      # Remove following to disable basic authentication
      BASIC_AUTH: admin:admin
      # Remove following line to get certs from Let's Encrypt
      TLS_INTERNAL: true
<<<<<<< HEAD
    restart: unless-stopped
=======

      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
      
>>>>>>> 68020cb (phase 1 of caddy TLS test)
    cap_add:
      - NET_ADMIN
