version: '3.9'
services:
    gateway-sshd:
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - gateway
    gateway:
        image: fractalnetworks/selfhosted-gateway:latest
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        networks:
            - gateway


networks:
    gateway:
        external: true


