version: '3.9'
services:
    gateway-sshd:
        build: .
        ports:
            - 2222:22
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - gateway
    gateway:
        image: fractalnetworks/selfhosted-gateway:latest
        ports:
            - 8000:80
            - 8443:443
        environment:
            NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        networks:
            - gateway


networks:
    gateway:
        external: true


