version: '3.9'

networks:
  gateway:
      external: true

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default-nginx-ssl.conf:/etc/nginx/templates/default-ssl.conf.template
    networks:
      - gateway
