name: CI

on:
  push:
    branches:
      - '**' # This will run the workflow on every push to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build images
      run: make docker

    - name: Launch gateway and create link on gateway
      run: make link-ci GATEWAY=gateway-sshd FQDN=app.example.com EXPOSE=app:3000

    #- name: Ensure link works by making request to app.example.com
    #  run: curl --resolve app.example.com:443:127.0.0.1 http://app.example.com:443


    - name: Cleanup
      run: docker compose -f ./ci/docker-compose.yaml down