name: CI

on:
  push:
    branches:
      - '**' # This will run the workflow on every push to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Launch gateway and create link on gateway
      run: make link-ci
